export const tableData = [

{"id":1,"country":"Portugal","company":"Thoughtbeat","footprint":18},
{"id":2,"country":"Czech Republic","company":"Eayo","footprint":65},
{"id":3,"country":"Brazil","company":"Feedfish","footprint":5},
{"id":4,"country":"China","company":"Tazz","footprint":98},
{"id":5,"country":"Brazil","company":"Fatz","footprint":98},
{"id":6,"country":"Indonesia","company":"Snaptags","footprint":52},
{"id":7,"country":"Thailand","company":"Oyoyo","footprint":64},
{"id":8,"country":"Nicaragua","company":"JumpXS","footprint":25},
{"id":9,"country":"Israel","company":"Tagchat","footprint":87},
{"id":10,"country":"Morocco","company":"Leenti","footprint":80},
{"id":11,"country":"France","company":"Lajo","footprint":43},
{"id":12,"country":"China","company":"Realblab","footprint":6},
{"id":13,"country":"Belarus","company":"Snaptags","footprint":58},
{"id":14,"country":"China","company":"Realbuzz","footprint":77},
{"id":15,"country":"Mali","company":"Realbridge","footprint":54},
{"id":16,"country":"Russia","company":"Kamba","footprint":83},
{"id":17,"country":"Indonesia","company":"Meembee","footprint":48},
{"id":18,"country":"China","company":"Omba","footprint":14},
{"id":19,"country":"South Africa","company":"Cogilith","footprint":45},
{"id":20,"country":"Peru","company":"Wikido","footprint":47},
{"id":21,"country":"Macedonia","company":"Demimbu","footprint":30},
{"id":22,"country":"China","company":"Yambee","footprint":43},
{"id":23,"country":"Spain","company":"Youtags","footprint":53},
{"id":24,"country":"Spain","company":"Ozu","footprint":42},
{"id":25,"country":"France","company":"Devpulse","footprint":64},
{"id":26,"country":"Palestinian Territory","company":"Oyondu","footprint":18},
{"id":27,"country":"Poland","company":"Fivechat","footprint":85},
{"id":28,"country":"France","company":"Livetube","footprint":67},
{"id":29,"country":"United States","company":"Babbleset","footprint":6},
{"id":30,"country":"Malaysia","company":"Brainlounge","footprint":85},
{"id":31,"country":"Peru","company":"Trilith","footprint":86},
{"id":32,"country":"Indonesia","company":"Skiba","footprint":62},
{"id":33,"country":"Japan","company":"Roombo","footprint":46},
{"id":34,"country":"Slovenia","company":"Shufflester","footprint":84},
{"id":35,"country":"Colombia","company":"Blogtag","footprint":10},
{"id":36,"country":"Poland","company":"Oyoba","footprint":20},
{"id":37,"country":"China","company":"Browsedrive","footprint":54},
{"id":38,"country":"China","company":"Voomm","footprint":17},
{"id":39,"country":"Cape Verde","company":"Tagchat","footprint":42},
{"id":40,"country":"Zimbabwe","company":"Kare","footprint":47},
{"id":41,"country":"Russia","company":"Photofeed","footprint":88},
{"id":42,"country":"Indonesia","company":"Jabbertype","footprint":75},
{"id":43,"country":"Brazil","company":"Topiclounge","footprint":14},
{"id":44,"country":"Ukraine","company":"Voonder","footprint":53},
{"id":45,"country":"China","company":"Ailane","footprint":59},
{"id":46,"country":"Greece","company":"Yakidoo","footprint":89},
{"id":47,"country":"Russia","company":"Aimbo","footprint":59},
{"id":48,"country":"Ireland","company":"Yodoo","footprint":7},
{"id":49,"country":"Ukraine","company":"Tagcat","footprint":81},
{"id":50,"country":"China","company":"Thoughtworks","footprint":13},
{"id":51,"country":"Tanzania","company":"Youfeed","footprint":13},
{"id":52,"country":"Indonesia","company":"Pixope","footprint":63},
{"id":53,"country":"United States","company":"Meetz","footprint":40},
{"id":54,"country":"South Africa","company":"Bubblemix","footprint":63},
{"id":55,"country":"Denmark","company":"Babbleset","footprint":35},
{"id":56,"country":"China","company":"Devcast","footprint":54},
{"id":57,"country":"Nigeria","company":"Flipopia","footprint":99},
{"id":58,"country":"Philippines","company":"Aimbo","footprint":20},
{"id":59,"country":"Republic of the Congo","company":"Devbug","footprint":81},
{"id":60,"country":"Russia","company":"Brainsphere","footprint":67},
{"id":61,"country":"China","company":"Topicshots","footprint":83},
{"id":62,"country":"Philippines","company":"Minyx","footprint":98},
{"id":63,"country":"Russia","company":"Demimbu","footprint":19},
{"id":64,"country":"Indonesia","company":"Bluezoom","footprint":61},
{"id":65,"country":"Brazil","company":"Eamia","footprint":9},
{"id":66,"country":"Thailand","company":"Zoonder","footprint":99},
{"id":67,"country":"Philippines","company":"Vitz","footprint":61},
{"id":68,"country":"Indonesia","company":"Eare","footprint":22},
{"id":69,"country":"Indonesia","company":"Bubbletube","footprint":73},
{"id":70,"country":"Japan","company":"Wordware","footprint":44},
{"id":71,"country":"Dominican Republic","company":"Oloo","footprint":74},
{"id":72,"country":"Indonesia","company":"BlogXS","footprint":52},
{"id":73,"country":"South Korea","company":"Kazio","footprint":58},
{"id":74,"country":"China","company":"Bubblebox","footprint":49},
{"id":75,"country":"France","company":"Shuffledrive","footprint":36},
{"id":76,"country":"Brazil","company":"Skidoo","footprint":73},
{"id":77,"country":"China","company":"Zoombox","footprint":60},
{"id":78,"country":"France","company":"Devify","footprint":58},
{"id":79,"country":"Argentina","company":"Browsetype","footprint":88},
{"id":80,"country":"Portugal","company":"Mynte","footprint":58},
{"id":81,"country":"Peru","company":"Yata","footprint":24},
{"id":82,"country":"Syria","company":"Avamm","footprint":86},
{"id":83,"country":"Indonesia","company":"Voonte","footprint":7},
{"id":84,"country":"Pakistan","company":"Photobean","footprint":49},
{"id":85,"country":"France","company":"Skimia","footprint":19},
{"id":86,"country":"Japan","company":"Snaptags","footprint":61},
{"id":87,"country":"China","company":"Cogibox","footprint":1},
{"id":88,"country":"Philippines","company":"Tazzy","footprint":25},
{"id":89,"country":"Brazil","company":"Dabshots","footprint":52},
{"id":90,"country":"Philippines","company":"Oyoloo","footprint":98},
{"id":91,"country":"China","company":"Snaptags","footprint":42},
{"id":92,"country":"Indonesia","company":"Tavu","footprint":87},
{"id":93,"country":"France","company":"Mynte","footprint":71},
{"id":94,"country":"Japan","company":"Babbleopia","footprint":25},
{"id":95,"country":"China","company":"Youspan","footprint":10},
{"id":96,"country":"Russia","company":"Reallinks","footprint":83},
{"id":97,"country":"Brazil","company":"Youspan","footprint":89},
{"id":98,"country":"Philippines","company":"Muxo","footprint":77},
{"id":99,"country":"Russia","company":"Dynabox","footprint":40},
{"id":100,"country":"Philippines","company":"Skippad","footprint":27}
]